registries:
- name: gcr.io/c-staging
  service-account: sa@robot.com
  src: true
- name: us.gcr.io/some-prod
  service-account: sa@robot.com
- name: eu.gcr.io/some-prod
  service-account: sa@robot.com
- name: asia.gcr.io/some-prod
  service-account: sa@robot.com
